# Gopkg.toml example

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/asecurityteam/transportd"
  version = "^0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/asecurityteam/settings"

[[constraint]]
  name = "github.com/Jeffail/benthos"
  # version = "^2.2.0"
  revision = "bdd5e353ea72a5805e80be84c3ebafa9acba2465"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"
